# Generated by Django 4.2.7 on 2023-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
