# Generated by Django 4.2.7 on 2023-12-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentmodel_email_paymentmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='refernce_id',
            new_name='reference_id',
        ),
    ]
