# Generated by Django 4.2.7 on 2023-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_refernce_id_paymentmodel_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='reference_id',
            field=models.CharField(max_length=150),
        ),
    ]
