version: '3.8'

services:
  django_app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/env1/static
    env_file:
      - .env

  nginx:
    build: ./Nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/env1/static
    depends_on:
      - django_app

volumes:
  static:
