# Generated by Django 3.2.23 on 2023-11-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socities', '0002_auto_20231126_2220'),
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_soc', to='socities.societies'),
        ),
    ]
