# Generated by Django 4.2.7 on 2023-11-12 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clergy_name', models.CharField(max_length=150)),
                ('clergy_detail', models.TextField(blank=True)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_pic', models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images')),
            ],
        ),
    ]
