# Generated by Django 4.2.7 on 2023-11-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SocietiesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Base_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('alternative_number', models.PositiveIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], default='PLANS[0]', max_length=200, null=True)),
                ('next_of_kin', models.CharField(default='Nulll', max_length=150)),
                ('next_of_kin_number', models.PositiveIntegerField(null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images')),
                ('about_user', models.TextField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Socities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SocietiesApp.societies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
