# Generated by Django 3.2.23 on 2023-11-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverticement_name', models.CharField(max_length=150)),
                ('adverticement_image', models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images')),
            ],
        ),
    ]
