# Generated by Django 4.2.7 on 2023-12-05 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_custombaseuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
