# Generated by Django 4.2.7 on 2023-12-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_custombaseuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
