# Generated by Django 4.2.7 on 2023-12-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_custombaseuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='login_detail',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
