# Generated by Django 4.2.7 on 2023-12-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_custombaseuser_login_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombaseuser',
            name='login_detail',
        ),
    ]
