# Generated by Django 4.2.7 on 2023-12-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_saint', models.CharField(max_length=150)),
                ('life_of_saint', models.TextField(blank=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/variac.jpeg/', null=True, upload_to='images')),
            ],
        ),
    ]
